### ISSUE TITLE
Uncaught ErrorException after modifying file

### ISSUE THREAD

**Issue by abrace** [lvht/phpcd.vim#100]
An Uncaught ErrorException can sometimes occur after modifying a file. This happens when the file contains PHP code but does not define a class. To reproduce:

1. edit a PHP file that does not define a class
2. modify and then write the file
3. edit a different PHP file in the project 

At this point I get:
```
PHP Fatal error:  Uncaught ErrorException: Uninitialized string offset: 0 in /Users/username/.vim/bundle/phpcd.vim/vendor/composer/ClassLoader.php:375
```

I'm using NVIM v0.2.0 on macOS 10.12.6 .

I've been able to stop the error locally by adding this code to the beginning of PHPID::update():
```
if ($class_name == '\\') {
    return;
}
```

Full stack trace:
```
PHP Fatal error:  Uncaught ErrorException: Uninitialized string offset: 0 in /Users/username/.vim/bundle/phpcd.vim/vendor/composer/ClassLoader.php:375
Stack trace:
#0 /Users/username/.vim/bundle/phpcd.vim/vendor/composer/ClassLoader.php(375): {closure}(8, 'Uninitialized s...', '/Users/username...', 375, Array)
#1 /Users/username/.vim/bundle/phpcd.vim/vendor/composer/ClassLoader.php(351): Composer\Autoload\ClassLoader->findFileWithExtension('', '.php')
#2 /Users/username/.vim/bundle/phpcd.vim/vendor/composer/ClassLoader.php(321): Composer\Autoload\ClassLoader->findFile('')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('')
#4 [internal function]: spl_autoload_call('')
#5 /Users/username/.vim/bundle/phpcd.vim/php/PHPID.php(195): ReflectionClass->__construct('\\')
#6 /Users/username/.vim/bundle/phpcd.vim/php/PHPID.php(40): PHPCD\PHPID->getClassInfo('\\')
#7 [internal function]: PHPCD\PHPID->update('\\')
#8 /Users/username/.vim/bundle/phpcd.vim/vendor/lvht/msgpack-rpc/src/AbstractServe in /Users/username/.vim/bundle/phpcd.vim/vendor/composer/ClassLoader.php on line 375
Fatal error: Uncaught ErrorException: Uninitialized string offset: 0 in /Users/username/.vim/bundle/phpcd.vim/vendor/composer/ClassLoader.php:375
Stack trace:
#0 /Users/username/.vim/bundle/phpcd.vim/vendor/composer/ClassLoader.php(375): {closure}(8, 'Uninitialized s...', '/Users/username...', 375, Array)
#1 /Users/username/.vim/bundle/phpcd.vim/vendor/composer/ClassLoader.php(351): Composer\Autoload\ClassLoader->findFileWithExtension('', '.php')
#2 /Users/username/.vim/bundle/phpcd.vim/vendor/composer/ClassLoader.php(321): Composer\Autoload\ClassLoader->findFile('')
#3 [internal function]: Composer\Autoload\ClassLoader->loadClass('')
#4 [internal function]: spl_autoload_call('')
#5 /Users/username/.vim/bundle/phpcd.vim/php/PHPID.php(195): ReflectionClass->__construct('\\')
#6 /Users/username/.vim/bundle/phpcd.vim/php/PHPID.php(40): PHPCD\PHPID->getClassInfo('\\')
#7 [internal function]: PHPCD\PHPID->update('\\')
#8 /Users/username/.vim/bundle/phpcd.vim/vendor/lvht/msgpack-rpc/src/AbstractServe in /Users/username/.vim/bundle/phpcd.vim/vendor/composer/ClassLoader.php on line 375
```

**Comment by abrace** [comment]
Problem solved, thank you.
