### ISSUE TITLE
Please, need some assistance

### ISSUE THREAD

**Issue by wysiecki** [lvht/phpcd.vim#101]
Hi, your plugin looks very cool, and i thank you for your time.
But have trouble to get it working.
some info first:
vim8, php7.0, ubuntu xenial, yii2 project
Plugins:
vim-airline, syntastic, ag, nerdtree, supertab, vim-repeat, fugitve

First i could not get it working at all, mean, the server was/is running, so the setup process went fine.
wysiecki  4724  4721  0 00:35 ?        00:00:00 php7.0 /home/wysiecki/.vim/plugged/phpcd.vim/php/main.php /home/wysiecki/projects/meditech json /home/wysiecki/projects/meditech/vendor/autoload.php 0

But there was no dir .phpcd, so i found out, that i have to call :call phpcd#Index()
Is that right ?
Now i have .phpcd with only two dirs inside extends and interfaces, with files in them, so looking ok. Should be something else in there?

Now, what i can omnicomplete are only static functions form some classes inside my own vendor dir, but not mine classes in the project.

On everything else i get Pattern not found, and that is what i see in the log (see below).
He can not find any of my classes, the paths of my files are correct, and the files and classes do exist.

Thanks in advance !
Martin

[2017-09-13 00:37:06] PHPCD.DEBUG: ReflectionException: Class common\models\ChangeArchive does not exist in /home/wysiecki/.vim/plugged/phpcd.vim/php/PHPCD.php:446 Stack trace: #0 /home/wysiecki/.vim/plugged/phpcd.vim/php/PHPCD.php(446): ReflectionClass->__construct('common\\models\\C...') #1 /home/wysiecki/.vim/plugged/phpcd.vim/php/PHPCD.php(419): PHPCD\PHPCD->typeByReturnType('common\\models\\C...', 'findOne', '/home/wysiecki/...') #2 [internal function]: PHPCD\PHPCD->functype('common\\models\\C...', 'findOne', '/home/wysiecki/...') #3 /home/wysiecki/.vim/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/AbstractServer.php(88): call_user_func_array(Array, Array) #4 /home/wysiecki/.vim/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/AbstractServer.php(65): Lvht\MsgpackRpc\ForkServer->doRequest(Array, Array) #5 /home/wysiecki/.vim/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/AbstractServer.php(44): Lvht\MsgpackRpc\ForkServer->onRequest(Array) #6 /home/wysiecki/.vim/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/ForkServer.php(32): Lvht\MsgpackRpc\ForkServer->onMessage(Array) #7 /home/wysiecki/.vim/plugged/phpcd.vim/php/main.php(41): Lvht\MsgpackRpc\ForkServer->loop() #8 {main} [] []
[2017-09-13 00:37:06] PHPCD.DEBUG: Class common\models\ChangeArchive does not exist [] []
[2017-09-13 00:40:51] PHPCD.DEBUG: Class \backend\controllers\base\ChangeArchiveController does not exist [] []
[2017-09-13 00:49:32] PHPCD.DEBUG: Class \backend\controllers\base\ChangeArchiveController does not exist [] []

**Comment by lvht** [comment]
It seems that your composer cannot load class like `common\models\ChangeArchive`, `\backend\controllers\base\ChangeArchiveController`. Be make sure your project follow the psr autoload standard. @wysiecki

**Comment by wysiecki** [comment]
Thanks for your light speed answer, yes, you are right, however, i can find my classes in the extends folder.
OK, so any way for a workaround, or do i have to create the autoload for my classes ?

**Comment by lvht** [comment]
@wysiecki try https://getcomposer.org/doc/04-schema.md#classmap

**Comment by wysiecki** [comment]
HAAAA, Yes, thank you, that worked out !

Just small last question, is that correct to run :call phpcd#Index() ? If so, then please add this to the doc. THX !

For any other, who might come up with same problem:

add to your composer.json following lines:
 "autoload": {
        "classmap": ["dirWithOwnClasses/"]
}

and do not forget to:
composer dump-autoload

**Comment by lvht** [comment]
no. PHPCD does need a index file for complementation. What phpcd#Index() does is to make a index for interface and its implementation, abstract class and its subclass. If you want to jump from a interface's method to its implementation, you need call phpcd#Index() first.

**Comment by wysiecki** [comment]
i'm so sorry to bug you, one really last. ;-)
The docblock info does not show up while scrolling through the list, like in your video.
Any quick fix ?

thanks
