### ISSUE TITLE
PHP fatal error

### ISSUE THREAD

**Issue by aceforeverd** [lvht/phpcd.vim#104]
I see this message when I opened a php file
```
PHP Fatal error:  Uncaught Error: Class 'MessagePackUnpacker' not found in /home/ace/.config/nvim/
dein.vim/repos/github.com/lvht/phpcd.vim/vendor/lvht/msgpack-rpc/src/MsgpackMessenger.php:18      
Stack trace:                                                                                      
#0 /home/ace/.config/nvim/dein.vim/repos/github.com/lvht/phpcd.vim/php/main.php(30): Lvht\MsgpackR
pc\MsgpackMessenger->__construct(Object(Lvht\MsgpackRpc\StdIo))                                   
#1 {main}                                                                                         
  thrown in /home/ace/.config/nvim/dein.vim/repos/github.com/lvht/phpcd.vim/vendor/lvht/msgpack-rp
c/src/MsgpackMessenger.php on line 18                                                             
Fatal error: Uncaught Error: Class 'MessagePackUnpacker' not found in /home/ace/.config/nvim/dein.
vim/repos/github.com/lvht/phpcd.vim/vendor/lvht/msgpack-rpc/src/MsgpackMessenger.php:18           
Stack trace:                                                                                      
#0 /home/ace/.config/nvim/dein.vim/repos/github.com/lvht/phpcd.vim/php/main.php(30): Lvht\MsgpackR
pc\MsgpackMessenger->__construct(Object(Lvht\MsgpackRpc\StdIo))                                   
#1 {main}                                                                                         
  thrown in /home/ace/.config/nvim/dein.vim/repos/github.com/lvht/phpcd.vim/vendor/lvht/msgpack-rp
c/src/MsgpackMessenger.php on line 18
```

**Comment by ArtBIT** [comment]
I've got the same error. I'm using:
 - NVIM v0.2.1-867-gd2cbc3118
 - Shougo/deoplete.nvim v4.0
 - and the latest junegunn/vim-plug

**Comment by lvht** [comment]
do you has the [msgpack](https://pecl.php.net/package/msgpack) extension installed?

**Comment by ArtBIT** [comment]
I thought I had. `sudo apt install php-msgpack` fixed it.
Thanks.

**Comment by aceforeverd** [comment]
Haven't installed php port of msgpack. fixed.
Thanks.
