### ISSUE TITLE
PHP Fatal error occurs at the opening php file

### ISSUE THREAD

**Issue by arwtyxouymz** [lvht/phpcd.vim#132]
Hi, I develop laravel project and I use deoplete.nvim and phpcd.vim for complemention.

When i open the php file, this errors occur.
```
PHP Warning:  Uncaught ErrorException: require(/Users/ryutaro/.config/nvim/dein/repos/github.com/lvht/phpcd.vim/php/../vendor/autoload.php): failed to open stream: No such file or directory in /Users/ryut
aro/.config/nvim/dein/repos/github.com/lvht/phpcd.vim/php/main.php:14
Stack trace:
#0 /Users/ryutaro/.config/nvim/dein/repos/github.com/lvht/phpcd.vim/php/main.php(14): {closure}(2, 'require(/Users/...', '/Users/ryutaro/...', 14, Array)
#1 /Users/ryutaro/.config/nvim/dein/repos/github.com/lvht/phpcd.vim/php/main.php(14): require()
#2 {main}
  thrown in /Users/ryutaro/.config/nvim/dein/repos/github.com/lvht/phpcd.vim/php/main.php on line 14
PHP Stack trace:
PHP   1. {main}() /Users/ryutaro/.config/nvim/dein/repos/github.com/lvht/phpcd.vim/php/main.php:0
PHP Fatal error:  main(): Failed opening required '/Users/ryutaro/.config/nvim/dein/repos/github.com/lvht/phpcd.vim/php/../vendor/autoload.php' (include_path='.:/Users/ryutaro/.phpbrew/php/php-7.0.25/lib/
php') in /Users/ryutaro/.config/nvim/dein/repos/github.com/lvht/phpcd.vim/php/main.php on line 14
PHP Stack trace:
PHP   1. {main}() /Users/ryutaro/.config/nvim/dein/repos/github.com/lvht/phpcd.vim/php/main.php:0
```

Probably phpcd.vim can't find `autoload.php`, but i created `.autoload.php` and `.phpcd.vim` following the Laravel Project Wiki.

Why does this problem occur?
I'm sorry my poor English.

**Comment by lvht** [comment]
phpcd.vim has its own autoload php file. you need go to the /Users/ryutaro/.config/nvim/dein/repos/github.com/lvht/phpcd.vim and run `composer update`.

However, I never test phpcd.vim under the dein.

![image](https://user-images.githubusercontent.com/2030591/36760435-c8431ac4-1c55-11e8-9aca-698544f13a18.png)

**Comment by arwtyxouymz** [comment]
@lvht Thanks!
I didn't run `composer update`.
