### ISSUE TITLE
CPU consumption

### ISSUE THREAD

**Issue by rosmanov** [lvht/phpcd.vim#133]
PHPCD consumes considerable amount of CPU resources even without invoking completion. For example, on my 4-core CPU a couple of PHPCD processes consume 2 cores entirely:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                  
24806 ruslan    20   0  152280  13316   2536 R 100.0  0.2  15:31.59 php /home/ruslan/projects/vimcfg/plugged/phpcd.vim/php/main.php /home/ruslan/www/vh msgp+
26363 ruslan    20   0  156376  21968   7260 R 100.0  0.3  12:41.67 php /home/ruslan/projects/vimcfg/plugged/phpcd.vim/php/main.php /home/ruslan/www/vh msgp+
```
I only opened a file and switched to another tab. I haven't even invoked completion.

The following is the output captured by `strace`:

```
$ strace -p 26363
recvfrom(3, "", 8192, MSG_DONTWAIT, NULL, NULL) = 0
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=3, revents=POLLIN|POLLHUP}])
recvfrom(3, "", 8192, MSG_DONTWAIT, NULL, NULL) = 0
poll([{fd=3, events=POLLIN|POLLERR|POLLHUP}], 1, 60000) = 1 ([{fd=3, revents=POLLIN|POLLHUP}])
...
```

The rows appear at a rate of around 3700 lines per second.

Nothing printed to `~/.phpcd.log`.

But it is not always reproduced. At times I can edit files for a half a day without issues. But sooner or later I have to `pfkill -f phpcd`. It happens more often with NeoVim than gVim.

[This](https://github.com/rosmanov/vimcfg) is my configuration.

## Update

I think I'm beginning to catch patterns. The issue appears shortly after
opening a PHP file and pressing <kbd>Ctrl</kbd>-<kbd>]</kbd> on a method call (e.g. `$obj->methodName()`). Often it works as expected -- I'm switched to the method definition. But sometimes it fails with the following message:
```
PHP Fatal error:  Uncaught ErrorException: fwrite(): send of 43 bytes failed with errno=32 Broken pipe in /home/ruslan/projects/vimcfg/plugged/phpcd.vim/vendo
r/lvht/msgpack-rpc/src/StdIo.php:25
Stack trace:                       
#0 [internal function]: {closure}(8, 'fwrite(): send ...', '/home/ruslan/pr...', 25, Array)
#1 /home/ruslan/projects/vimcfg/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/StdIo.php(25): fwrite(Resource id #2, '\x93\x02\xABvim_command\x91...')
#2 /home/ruslan/projects/vimcfg/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/MsgpackMessenger.php(37): Lvht\MsgpackRpc\StdIo->write('\x93\x02\xABvim_command\
x91...')
#3 /home/ruslan/projects/vimcfg/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/ForkServer.php(40): Lvht\MsgpackRpc\MsgpackMessenger->send(Array)
#4 /home/ruslan/projects/vimcfg/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/AbstractServer.php(107): Lvht\MsgpackRpc\ForkServer->write(Array)
#5 /home/ruslan/projects/vimcfg/plugged/phpcd.vim/php/PHPID.php(111): Lvht\MsgpackRpc\ForkServer->call('vim_command', Array)                   
#6 [internal  in /home/ruslan/projects/vimcfg/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/StdIo.php on line 25  
```

Immediately the PHPCD process consumes 100% of a CPU core or even a couple of
cores. After that, when I'm retrying to invoke <kbd>Ctrl</kbd>-<kbd>]</kbd> I get the following bunch of errors:

```
Error detected while processing function phpcd#JumpToDefinition[5]..phpcd#GetCurrentSymbolWithContext[54]..phpcd#GetCurrentNameSpace[1]..rpc#request:         
line    2:                                                                                                                                           
Invalid channel: 2
Error detected while processing function phpcd#JumpToDefinition[5]..phpcd#GetCurrentSymbolWithContext[54]..phpcd#GetCurrentNameSpace:
line    3:                                                                                                                           
E121: Undefined variable: namespace
E15: Invalid expression: [nsuse.namespace, nsuse.imports]
Error detected while processing function phpcd#JumpToDefinition[5]..phpcd#GetCurrentSymbolWithContext:
line   54:                                                                                            
E714: List required
line   56:         
E121: Undefined variable: current_namespace
E116: Invalid arguments for function phpcd#ExpandClassName
E15: Invalid expression: phpcd#ExpandClassName(word, current_namespace, current_imports)
line   61:                                                                              
E121: Undefined variable: symbol
E15: Invalid expression: [symbol, context, symbol_namespace, current_imports]
Error detected while processing function phpcd#JumpToDefinition:             
line    5:                                                      
E714: List required
line    6:         
E121: Undefined variable: symbol
E15: Invalid expression: symbol == ''
line   10:                           
E121: Undefined variable: symbol
E116: Invalid arguments for function phpcd#LocateSymbol
E15: Invalid expression: phpcd#LocateSymbol(symbol, symbol_context, symbol_namespace, current_imports)
line   11:                                                                                            
E121: Undefined variable: symbol_file
E15: Invalid expression: symbol_file == '' || symbol_file == v:false
line   30:                                                          
E121: Undefined variable: symbol_line
E116: Invalid arguments for function str2nr
E15: Invalid expression: str2nr(symbol_line) > 0
```

## Update 2

PHPCD process immediately starts consuming 100% of a CPU core when I create a new class:

- `:tabe path/to/file.php`

```
<?php

namespace Some\Namespace;

class ClassName
{
}
````
- `:w`

Just like that. Nothing special. I simply switch to new tab, write a class stub and save it.

## Update 3

Is reproduced only with *deoplete*.

**Comment by lvht** [comment]
sorry, I use neovim + deoplete but cannot reproduce this issue.

**Comment by rosmanov** [comment]
I have removed *deoplete* and installed *roxma/nvim-completion-manager*. So far everything works satisfactorily.
