### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'MessagePackUnpacker' not found

### ISSUE THREAD

**Issue by greencopper** [lvht/phpcd.vim#134]
I have just installed phpcd.vim using vimplug and the installation vent fine. As soon as I start neovim I get the following error:

```
PHP Fatal error:  Uncaught Error: Class 'MessagePackUnpacker' not found in .config/nvim/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/MsgpackMessenger.
php:18
Stack trace:
#0 .config/nvim/plugged/phpcd.vim/php/main.php(30): Lvht\MsgpackRpc\MsgpackMessenger->__construct(Object(Lvht\MsgpackRpc\StdIo))
#1 {main}
  thrown in .config/nvim/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/MsgpackMessenger.php on line 18
Fatal error: Uncaught Error: Class 'MessagePackUnpacker' not found in .config/nvim/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/MsgpackMessenger.php:1
8
Stack trace:
#0 .config/nvim/plugged/phpcd.vim/php/main.php(30): Lvht\MsgpackRpc\MsgpackMessenger->__construct(Object(Lvht\MsgpackRpc\StdIo))
#1 {main}
  thrown in .config/nvim/plugged/phpcd.vim/vendor/lvht/msgpack-rpc/src/MsgpackMessenger.php on line 18
```

Kind regards

**Comment by lvht** [comment]
You need install [php-msgpack](https://github.com/msgpack/msgpack-php) extension. Please read the README.md first.

**Comment by naimsplace** [comment]
Thanks, I overlooked that. Sorry.
