### ISSUE TITLE
Uncaught ErrorException concerning strpos

### ISSUE THREAD

**Issue by tostiheld** [lvht/phpcd.vim#186]
Hi,

I was typing away in vim and all of a sudden I started to get this message over and over again in :messages:

```
PHP Fatal error:  Uncaught ErrorException: strpos(): Non-string needles will be interpreted as strings in the future. Use an explicit chr() call to preserve the current behavior in /home/<redacted>/.vim/bundle/phpcd.vim/php/PHPCD.php:1005
Stack trace:
#0 [internal function]: {closure}()
#1 /home/<redacted>/.vim/bundle/phpcd.vim/php/PHPCD.php(1005): strpos()
#2 [internal function]: PHPCD\PHPCD->psr4ns()
#3 /home/<redacted>/.vim/bundle/phpcd.vim/vendor/lvht/msgpack-rpc/src/AbstractServer.php(88): call_user_func_array()
#4 /home/<redacted>/.vim/bundle/phpcd.vim/vendor/lvht/msgpack-rpc/src/AbstractServer.php(65): Lvht\MsgpackRpc\ForkServer->doRequest()
#5 /home/<redacted>/.vim/bundle/phpcd.vim/vendor/lvht/msgpack-rpc/src/AbstractServer.php(44): Lvht\MsgpackRpc\ForkServer->onRequest()
#6 /home/<redacted>/.vim/bundle/phpcd.vim/vendor/lvht/msgpack-rpc/src/ForkServer.php(32): Lvht\MsgpackRpc\ForkServer->onMessage()
#7 /home/<redacted>/.vim/bundle/phpcd.vim/php/main.php(41): Lvht\MsgpackRpc\ForkServer->loop()
#8 {main}
  thrown in /home/<redacted>/.vim/bundle/phpcd.vim/php/PHPCD.php on line 1005
```

Looks like some deprecation notice?

**Comment by tostiheld** [comment]
I believe it's because ```realpath()``` returned ```false``` at https://github.com/lvht/phpcd.vim/blob/master/php/PHPCD.php#L1004? If that indeed seems to be the issue, I can submit a pull request later if that's desired.
